feature(itchat): add UOS weixin desktop patch
blueset/efb-wechat-slave pull request #136
Opened 2022-07-13 16:36 UTC by shejialuo

It turns out that `wechat-uos` provided by Tencent still uses the web
interface, and someone finds the way to utilize the `wechat-uos` to
login into the web for the ones who cannot login by web. This commit
uses the information provided by the others. It does the three basic
things:

1. Change itchat `config.py` to add the corresponding version and
   `UOS_PATCH_EXTSPAM`.
2. Change itchat `components/login.py` to add the latest weixin check,
   `skey` field and `pass_ticket` field.
3. In order to get the message from weixin, eveytime the device ID
   should be changed, so this commit uses random string to generate
   the device ID.

However, this patch doesn't work for WeChat users.

2022-07-13 17:02 UTC, blueset requested changes
Considering Web WC is no longer available to “WeChat” users, I think this patch is mostly fine.

Can you add a one-line summary of your change to both the “Unreleased“ section of `/CHANGES.rst` and `efb-wechat-slave/efb_wechat_slave/vendor/itchat/CHANGES`?

2022-07-14 01:43 UTC, shejialuo commented
I have already changed the file. However, the puzzle thing is that I could not figure out the commit hash ID with only one commit message, So i use `[shejialuo] == [efb-wechat-slave#136]` to the CHANGELOG of itchat.

2022-07-14 02:25 UTC, blueset approved these changes

2022-07-14 02:26 UTC, merged

2022-07-16 07:01 UTC, whudwl commented
This is awesome! thank you so much!

2022-07-16 07:10 UTC, brryaa commented
You save the efb weixin users who cannot login by web. It's a great contribution. Thank you !

2022-07-18 00:20 UTC, jiz4oh commented
Thank you!

2022-07-19 08:02 UTC, hookjk100 commented
If you have any questions, you can communicate with “ efb-wechat 難民營” here: https://t.me/+UJz8XfH65xg1ZmU5