Adding a 'replace_emoticon' flag
blueset/efb-wechat-slave pull request #137
Opened 2022-07-25 12:50 UTC by realdeveloperongithub

Adding a 'replace_emoticon' flag to provide ways to disable emoticon replacing

2022-07-30 17:43 UTC, blueset requested changes
Left a comment in the code.

Also, can you add your change to `CHANGES.rst`?

2022-07-30 17:43 UTC, blueset commented on efb_wechat_slave/utils.py
> +def wechat_string_unescape(content: str, replace_emoticon: bool = True) -> str:
Look like no references of `wechat_string_unescape` is updated to pass in the new parameter.

2022-08-21 05:02 UTC, realdeveloperongithub commented on efb_wechat_slave/utils.py
> +def wechat_string_unescape(content: str, replace_emoticon: bool = True) -> str:
updated slave_message.py and CHANGES.rst

2022-08-21 14:54 UTC, realdeveloperongithub commented
updated slave_message.py and CHANGES.rst

2022-08-26 13:36 UTC, blueset approved these changes

2022-08-26 13:36 UTC, blueset commented
Thank you for the awesome contribution!

2022-08-26 13:36 UTC, merged